version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.3.0
  aws-cli: circleci/aws-cli@0.1.16


jobs:
  deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    environment:
      aws-access-key-id:
      aws-secret-access-key:
      aws-region:
    steps:
      - aws-cli/install
      # auth to aws
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          aws-region: AWS_REGION

      - checkout
      - run:
          name: Deploy
          command: |
            bash deploy.sh



workflows:
  version: 2
  build_and_deploy:
    jobs:

  #    - aws-ecr/build-and-push-image:
          # auth to aws

   #       aws-access-key-id: AWS_ACCESS_KEY
    #      aws-secret-access-key: AWS_SECRET_ACCESS_KEY
     #     region: AWS_REGION

          # build and push to ecr
      #    dockerfile: Dockerfile
       #   account-url: AWS_ECR_ACCOUNT_URL
        #  repo: megaparts
         # tag: latest

          # general config
         # attach-workspace: true
         # context: value
         # filters:
         #  branches:
          #    only:
           #     - master


      - deploy:
        #  requires:
         #   - aws-ecr/build-and-push-image
         # context: value
          filters:
            branches:
              only:
                - master
